# Header
menu:
  Home: /
  About: /about
  About Me: /about-me
  Guest Book: /guestbook
  Contact Me: /contact
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tagcloud
- recent_posts
- hot_comments
# - links

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter: 
google_plus:
fb_admins:
fb_app_id:

#duoshuo
duoshuo: xfeng
